export const endpoints = {
  Login: "/api/Login/Login",
  TwoFactorAuthentication: "/api/Login/ValidateTwoFactorAuthentication",
  sendOtp: "/api/Common/SendOtp",
  GetPNL: "/api/PNL/GetPNL",
  GetPNLAccountDetailsPdf: "/api/PNL/GetPNLAccountDetailsPdf",
  getDropDown: "/api/Common/MGetDropDowns",
  getDormantReport: "/api/Common/GetDormantReport",
  getDormantExcel: "/api/Common/GetDormantExcel",
  lastTradeDate: "/api/Client/LastTradeDate",
  GetQuaterlyPayoutGrid: "/api/Common/GetQuaterlyPayoutGrid",
  SLBMHoldingsReport: "/api/ShortAllocation/SLBMHoldingsReport",
  SLBMHoldingsReportExcel: "/api/ShortAllocation/SLBMHoldingsReportExcel",
  GetCoreAlertsReport: "/api/Common/GetCoreAlertsReport",
  getMenus: "/api/Menu/GetMenus",
  shortAllocation: "/api/ShortAllocation/InsertShortAllocationData",
  SLBMHoldingsUpload: "/api/ShortAllocation/SLBMHoldingsUpload",
  ClientCash: "/api/Client/ClientCash",
  T6Selling: "/api/ShortAllocation/T6Selling",
  Last7dayBrokerage: "/api/Client/Last7DaysBrok",
  GetClientStatusCnt: "/api/Client/GetClientStatusCnt",
  DealerPerformance: "/api/MIS/DEALERPERFORMANCE",
  forgetPassword: "/api/Login/ForgetPassword",
  ClientDetails: "/api/Client/ClientDetails",
};
