export const endpoints = {
  Login: "/api/Login/Login",
  TwoFactorAuthentication: "/api/Login/ValidateTwoFactorAuthentication",
  sendOtp: "/api/Common/SendOtp",
  GetPNL: "/api/PNL/GetPNL",
  GetPNLStatement: "/api/PNL/GetPNLStatement",
  UnblockUser: "/api/Login/UnblockUser",
  GetPNLAccountDetailsPdf: "/api/PNL/GetPNLAccountDetailsPdf",
  getDropDown: "/api/Common/MGetDropDowns",
  getDormantReport: "/api/Common/GetDormantReport",
  getDormantExcel: "/api/Common/GetDormantExcel",
  lastTradeDate: "/api/Client/LastTradeDate",
  GetQuaterlyPayoutGrid: "/api/Common/GetQuaterlyPayoutGrid",
  SLBMHoldingsReport: "/api/ShortAllocation/SLBMHoldingsReport",
  SLBMHoldingsReportExcel: "/api/ShortAllocation/SLBMHoldingsReportExcel",
  GetCoreAlertsReport: "/api/Common/GetCoreAlertsReport",
  getMenus: "/api/Menu/GetMenus",
  shortAllocation: "/api/ShortAllocation/InsertShortAllocationData",
  SLBMHoldingsUpload: "/api/ShortAllocation/SLBMHoldingsUpload",
  ClientCash: "/api/Client/ClientCash",
  T6Selling: "/api/ShortAllocation/T6Selling",
  Last7dayBrokerage: "/api/Client/Last7DaysBrok",
  GetAPRevenue: "/api/AP/GetAPRevenue",
  GetClientStatusCnt: "/api/Client/GetClientStatusCnt",
  DealerPerformance: "/api/MIS/DEALERPERFORMANCE",
  forgetPassword: "/api/Login/ForgetPassword",
  ClientDetails: "/api/Client/ClientDetails",
  getUpcompingDormantReport: "/api/Common/GetUpcomingDormantReport",
  GetBirthdayList: "/api/Common/GetBirthdayList",
  ClientDashboard: "/api/Client/ClientDashboard",
  GetBrokerageDetails: "/api/Brokerage/GetBrokerageDetails",
  GetBrokeragePlans: "/api/Brokerage/GetBrokeragePlans",
  UpdateClientBrokerageModification:
    "/api/Brokerage/UpdateClientBrokerageModification",
  GetBrokerageModificationHistory:
    "/api/Brokerage/GetBrokerageModificationHistory",
  ClientSegmentBrok: "/api/Client/ClientSegmentBrok",
  DPDebitRecovery: "/api/Client/DPDebitRecovery",
  DPEmail: "/api/Client/DPEmail",
  getFundamentalOverview: "/Fundamental/fundamental",
  getFundamentalShareholding: "/Fundamental/Shareholding",
  getFundamentalcashflow: "/Fundamental/cashflow",
  getFundamentalDividend: "/Fundamental/Dividend",
  getFundamentalBonus: "/Fundamental/Bonus",
  getFundamentalSplit: "/Fundamental/Split",
  getFundamentalBoardMeeting: "/Fundamental/Boardmeeting",
  getFundamentalBalanceSheet: "/Fundamental/balancesheet",
  getFundamentalAnnualPNL: "/Fundamental/Annually",
  getFundamentalQuaterlyPNL: "/Fundamental/Quaterly",
  getFundamentalRatios: "/Fundamental/Ratios",
  getFundamentalNewsfeed: "/Fundamental/newsfeed",
  ComplainceReport: "/api/Compliance/ComplianceData",
  ComplianceData: "/api/Compliance/ComplianceData",
  ComplainceFileDownload: "/api/Compliance/ComplainceFileDownload",
  ComplainceFileUpload: "/api/Compliance/ComplainceFileUpload",
  DashboardNudge: "/api/Dashboard/DashboardNudge",
  ViewMarketingMaterials: "/api/Dashboard/ViewMarketingMaterials",
  getInUpMarketMaterial: "/api/Dashboard/InsertUpdateMakertingMaterials",
  getInUpRegAnnoucement: "/api/Dashboard/InsertUpdateRegulatoryAnnoucement",
  viewRegAnnoucement: "/api/Dashboard/viewRegulatoryAnnoucement",
  ChangePassword: "api/Login/ChangePassword",
  GetAPDashboard: "api/AP/GetAPDashboard",
  ScripSearch: "api/AP/ScripSearch",
  UploadTradeFile: "/api/PreTrade/UploadTradeFile",
  GetAllRecords: "/api/PreTrade/GetAllRecords",
  GetPreTradeReport: "/api/PreTrade/GetPreTradeReport",
  GetPendingApproveStatus: "/api/PreTrade/GetPendingApproveStatus",
  SavePreTradeApproveStatus: "/api/PreTrade/SavePreTradeApproveStatus",
  GetBrokerageModificationStatus:
    "/api/Brokerage/GetBrokerageModificationStatus",
  GetBrokerageKycStatus: "/api/Brokerage/GetBrokerageKycStatus",
  UpdateBrokerageKycStatus: "/api/Brokerage/UpdateBrokerageKycStatus",
  GetBrokerageRHStatus: "/api/Brokerage/GetBrokerageRHStatus",
  UpdateBrokerageRHStatus: "/api/Brokerage/UpdateBrokerageRHStatus",
  GetBrokerageModificationValidity:
    "/api/Brokerage/GetBrokerageModificationValidity",
  GetClientWiseBrokerage: "/api/Brokerage/GetClientWiseBrokerage",
  GetTechExcelApiResponse: "/api/Brokerage/GetTechExcelApiResponse",
  CTCLActivityReport: "/api/MIS/CTCLActivityReport",
  TradingPatternReport: "/api/MIS/TradingPatternReport",
  DetailedTradingPatternReport: "/api/MIS/DetailedTradingPatternReport",
};
